language: java
dist: trusty
sudo: false
jdk:
  - openjdk8


before_deploy:
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}

deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
    - target/jobdeploy-assembly-*-deploy.tar.gz
  skip_cleanup: true
  on:
    tags: true
