language: java
dist: trusty
sudo: false
jdk:
  - openjdk8


before_deploy:
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}
  - mvn package
  - mvn versions:revert
  - export APP_JAR=$(ls target/jobdeploy-assembly*-deploy.tar.gz|head -n 1)


deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
    - $APP_JAR
  skip_cleanup: true
  on:
    tags: true
