language: java
dist: trusty
sudo: false
jdk:
  - openjdk8


before_deploy:
  - mvn versions:set -DnewVersion=${TRAVIS_TAG}
  - sed -i 's/^[[:space:]]*public[[:space:]]\{1,\}static[[:space:]]\{1,\}final[[:space:]]\{1,\}String[[:space:]]\{1,\}DEPLOY_VERSION[[:space:]]\{1,\}=.*$/  public static final String DEPLOY_VERSION = "'$TRAVIS_TAG'";/' core/src/main/java/com/devhc/jobdeploy/config/Constants.java
  - mvn clean package
  - mvn versions:revert
  - export APP_JAR=$(ls target/jobdeploy-assembly*-deploy.tar.gz|head -n 1)
  - echo $APP_JAR


deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file:
    - $APP_JAR
  skip_cleanup: true
  on:
    tags: true
