#!/bin/bash
[[ $DEBUG == true  ]] && set -x



usage() {
  cat <<END
Usage:
  `basename $0` [help|--help|-h]
  `basename $0` [install_path]
  default <install_path>   = /opt/jobdeploy
Environments:
  DEBUG - if set to true, enable 'set -x'
After the script success, you need also:
  - sudo ln -sf {install_path}/deploy /usr/bin/deploy
END
}
die() {
  local err=$?
  (( err != 0 )) || err=1
  echo ERROR: "$@" >&2
  exit $err
}
die_with_usage() {
  usage >&2
  die "$@"
}
check_dep(){
  local cmd=$1
  command -v $cmd $ &>/dev/null || die "Can't find $cmd command!"
}
check_java(){
  check_dep java
  java_version=`java -version 2>&1 | awk -F '"' '/version/ {print $2}'`
  if [[ "$java_version" < "1.6" ]];then
    die "need jdk >= 1.6"
  fi
}

case $# in
    (0|1) ;;
    (*) die_with_usage "Invalid options." ;;
esac
case "$1" in
	(help|--help|-h) usage; exit 0 ;;
esac

check_java
check_dep mvn


INSTALL_PATH=$1
if [ -z $INSTALL_PATH ];then
    echo "install path not set,set default INSTALL_PATH=/opt/jobdeploy"
    INSTALL_PATH=/opt/jobdeploy
fi
REPO=https://github.com/all3n/jobdeploy.git

echo $INSTALL_PATH
if [ -z $INSTALL_PATH ];then
    echo "install path empty..."
    exit
fi
mkdir -p $INSTALL_PATH
echo "start build "
SRC_DIR="."
INSTALL_TEMP_DIR=`mktemp -d /tmp/jobdeploy.install.XXXXXX`
trap "rm -rf $INSTALL_TEMP_DIR" EXIT

if [ ! -d .git ];then
    SRC_DIR="$INSTALL_TEMP_DIR/jobdeploy"
    git clone $REPO $SRC_DIR
    pushd $SRC_DIR >/dev/null 2>&1
fi

echo "start build jobdeploy"
./mvnw clean
./mvnw package -DskipTests=true -Paliyun
echo "end build jobdeploy"


TAR_FILE=`ls target/jobdeploy-core-*.tar.gz|head -n 1`


rm -rf $INSTALL_PATH
mkdir -p $INSTALL_PATH
tar -zxvf $TAR_FILE -C $INSTALL_PATH

echo "INSTALL SUCCESS!!"
echo "PLEASE ADD $INSTALL_PATH in the env PATH first time"
echo "OR sudo ln -sf $INSTALL_PATH/deploy /usr/bin/deploy"

