#!/bin/bash
[[ $DEBUG == true  ]] && set -x


DEFAULT_DIR=$HOME/opt/jobdeploy

usage() {
  cat <<END
Usage:
  `basename $0` [help|--help|-h]
  `basename $0` [install_path]
  default <install_path>   = $HOME/opt/jobdeploy
Environments:
  DEBUG - if set to true, enable 'set -x'
After the script success, you need also:
  - sudo ln -sf {install_path}/deploy /usr/bin/deploy
END
}
die() {
  local err=$?
  (( err != 0 )) || err=1
  echo ERROR: "$@" >&2
  exit $err
}
die_with_usage() {
  usage >&2
  die "$@"
}
check_dep(){
  local cmd=$1
  command -v $cmd $ &>/dev/null || die "Can't find $cmd command!"
}
check_java(){
  check_dep java
  java_version=`java -version 2>&1 | awk -F '"' '/version/ {print $2}'`
  if [[ "$java_version" < "1.6" ]];then
    die "need jdk >= 1.6"
  fi
}
get_deploy_dir(){
    which deploy &>/dev/null
    if [[ $? -eq 0 ]];then
        echo $(dirname $(dirname $(which deploy)))
    else
        echo $DEFAULT_DIR
    fi
}

case $# in
    (0|1) ;;
    (*) die_with_usage "Invalid options." ;;
esac
case "$1" in
	(help|--help|-h) usage; exit 0 ;;
esac

check_java
check_dep mvn



INSTALL_PATH=$1
if [ -z $INSTALL_PATH ];then
    echo "install path not set,set default INSTALL_PATH=/opt/jobdeploy"
    INSTALL_PATH=$(get_deploy_dir)
fi
REPO=https://github.com/all3n/jobdeploy.git

echo $INSTALL_PATH
if [ -z $INSTALL_PATH ];then
    echo "install path empty..."
    exit
fi
mkdir -p $INSTALL_PATH
echo "start build "
SRC_DIR="."
INSTALL_TEMP_DIR=`mktemp -d /tmp/jobdeploy.install.XXXXXX`
trap "rm -rf $INSTALL_TEMP_DIR" EXIT

if [ ! -d .git ];then
    SRC_DIR="$INSTALL_TEMP_DIR/jobdeploy"
    git clone $REPO $SRC_DIR
    pushd $SRC_DIR >/dev/null 2>&1
fi

echo "start build jobdeploy"
./script/build-release.sh
if [[ $? -ne 0 ]];then
  echo "build fail"
  exit
fi
echo "end build jobdeploy"

rm -rf $INSTALL_PATH
mkdir -p $INSTALL_PATH

tar -zxvf $SRC_DIR/target/jobdeploy-assembly-0.0.1-SNAPSHOT-deploy.tar.gz -C $INSTALL_PATH

SHELL_RC=$HOME/.bashrc
if [[ -f $HOME/.zshrc ]];then
    SHELL_RC=$HOME/.zshrc
fi
if ! $(cat $SHELL_RC|grep $INSTALL_PATH >/dev/null 2>&1);then
    echo "export PATH=$INSTALL_PATH/bin:\$PATH " >> $SHELL_RC
fi
