FROM centos:7.9.2009
ENV JD_HOME /opt/jobdeploy


RUN yum install -y make python3 wget  java-1.8.0-openjdk java-1.8.0-openjdk-devel openssh-clients && yum clean all
RUN wget --no-check-certificate https://dlcdn.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz -O /tmp/maven.tar.gz \
  && tar -zxvf /tmp/maven.tar.gz -C /opt \
  && rm /tmp/maven.tar.gz && ln -s /opt/apache-maven-3.6.3 /opt/maven

ENV PATH /opt/jobdeploy/bin:/opt/maven/bin:$PATH
VOLUME /app
WORKDIR /app
RUN useradd deploy
RUN mkdir -p $JD_HOME/logs && chown deploy:deploy $JD_HOME/logs
USER deploy
CMD ["bash"]
