#!/bin/bash
if [[ -L $0 ]];then
    SCRIPT=`readlink $0`
else
    SCRIPT=$0
fi
bin=`dirname "$SCRIPT"`
export APPDIR=`cd "$bin/../"; pwd`
LOGDIR=$APPDIR/logs
JAR_FILE=`ls -l $APPDIR/jobdeploy-*.jar|head -n 1`
MAIN_CLASS=com.devhc.jobdeploy.App
JOBDEPLOY_GIT_REPO=https://github.com/all3n/jobdeploy.git
CMD=$1
if [ ! -d $LOGDIR ];then
    mkdir -p $LOGDIR
    chmod 777 $LOGDIR
fi
LOGFILE=$LOGDIR/`whoami`-deploy.log
if [ "$CMD" = "--update" ];then
    APPDIR_REPO=`mktemp -d /tmp/jobdeploy-XXXXX`
    trap "rm -rf $APPDIR_REPO" EXIT
    echo "start to update deploy to latest.."
    rm -rf  $APPDIR_REPO
    mkdir -p $APPDIR_REPO
    chmod 777 $APPDIR_REPO
    git clone $JOBDEPLOY_GIT_REPO $APPDIR_REPO
    mvn package -DskipTests=true -f $APPDIR_REPO/pom.xml
    TAR_FILE=`ls $APPDIR_REPO/target/*.tar.gz|head -n 1`
    tar -zxvf $TAR_FILE -C $APPDIR
    mkdir -p $LOGDIR
    chmod 777 $LOGDIR
    echo "update job success"
else
    java -Dlog.file=${LOGFILE} -cp $APPDIR/conf:$APPDIR/*:$APPDIR/libs/*:$APPDIR/plugins $MAIN_CLASS "$@"
fi
