name: JobDeployCI
run-name: ${{ github.actor }} jobdeploy CI 🚀
on:
    push:
        tags:
            - '*'
jobs:
  Release-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build With Maven
        run: |
          ./script/build-release.sh
      - name: release_please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: maven
          command: github-release
          package-name: release-please-action
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./target/jobdeploy-assembly-0.0.1-SNAPSHOT-deploy.tar.gz
          asset_name: jobdeploy-assembly-0.0.1-SNAPSHOT-deploy.tar.gz
          asset_content_type: application/gzip

